### ISSUE TITLE
needs testing main included in repo w/ assets required

### ISSUE THREAD

**Issue by sharkbound** [AnicetNgrt/flore1#1]
i am in the process of updating some of the code to use newer python features, and there is no testing file to verify nothing broke

**Comment by AnicetNgrt** [comment]
I'll make one real quick

**Comment by AnicetNgrt** [comment]
You now have a code to test in "demos/reddit demo"
I will add more in the future
Thanks for the help 👍

**Comment by AnicetNgrt** [comment]
Also could you compare fps on your build and my build, I want that we make sure there is no performance drop too :) Thanks
